---
title: "Project EDA"
output: html_document
date: "2022-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```


```{r} 

data <- read.csv("merged_data.csv")  

subData = data[,c(4,16,17,18,19,20,21,22,23,24,25)]
head(subData)
summary(subData)

```
```{r}
price <- subData$price
totCredAmt <- subData$total_credit_amt
#plot(totCredAmt, price,xlab="Total Credit Amount",ylab="Price",main="Price vs. Credit #Amount")
#abline(lm(price~totCredAmt),col="red")

```

```{r}
data1 = subData[c(1,2,3,4)]
data2 = subData[c(1,5,6,7)]
data3 = subData[c(1,8,9,10,11)]
pairs(data1)
pairs(data2)
pairs(data3)

```

```{r}
corPrice_creditAmt = cor(subData$total_credit_amt,subData$price)
corPrice_creditAmt

corPrice_taxIncome = cor(subData$taxable_income_amt,subData$price)
corPrice_taxIncome

corPrice_mortAmt = cor(subData$mortgageint_amt,subData$price)
corPrice_mortAmt

corPrice_pMort = cor(subData$p_mortgageint_nr,subData$price)
corPrice_pMort

corPrice_incomeTax = cor(subData$inctax_amt,subData$price)
corPrice_incomeTax

corPrice_pUnemp = cor(subData$p_unemploy_nr,subData$price)
corPrice_pUnemp

corPrice_agiAmt = cor(subData$agi_amt,subData$price)
corPrice_agiAmt

corPrice_numDep = cor(subData$num_dependents,subData$price)
corPrice_numDep

corPrice_pReTax = cor(subData$p_re_taxes_nr,subData$price)
corPrice_pReTax

corPrice_agiBucket = cor(subData$agi_bucket,subData$price)
corPrice_agiBucket

```

#### Weak correlation between Price and taxable_income_amt, inctax_amt, and agi_amt. No correlation among other variables.

```{r}
price = subData$price
credit_amt = subData$total_credit_amt
par(mfrow=c(1,3))
boxplot(price~credit_amt,data=subData,col="orange",border="brown")

tax_income = subData$taxable_income_amt
boxplot(price~tax_income,data=subData,col="orange",border="brown")

mortg_amt = subData$mortgageint_amt
boxplot(price~mortg_amt,data=subData,col="orange",border="brown")

```


```{r}
par(mfrow=c(1,3))
pMort = subData$p_mortgageint_nr
boxplot(price~pMort,data=subData,col="orange",border="brown")

incomeTax = subData$inctax_amt
boxplot(price~incomeTax,data=subData,col="orange",border="brown")

pUnemp = subData$p_unemploy_nr
boxplot(price~pUnemp,data=subData,col="orange",border="brown")


```

```{r}
par(mfrow=c(1,3))
agi_amt = subData$agi_amt
boxplot(price~agi_amt,data=subData,col="orange",border="brown")

numDepend = subData$num_dependents
boxplot(price~numDepend,data=subData,col="orange",border="brown")

preTax = subData$p_re_taxes_nr
boxplot(price~preTax,data=subData,col="orange",border="brown")

```
```{r}
par(mfrow=c(1,3))
agi_bkt = subData$agi_bucket
boxplot(price~agi_bkt,data=subData,col="orange",border="brown")
```

Linearity Assumption

```{r}
price = subData$price
credit_amt = subData$total_credit_amt
tax_income = subData$taxable_income_amt
mortg_amt = subData$mortgageint_amt
pMort = subData$p_mortgageint_nr
incomeTax = subData$inctax_amt
pUnemp = subData$p_unemploy_nr
agi_amt = subData$agi_amt
numDepend = subData$num_dependents
preTax = subData$p_re_taxes_nr
agi_bkt = subData$agi_bucket

model = lm(price~credit_amt+tax_income+mortg_amt+pMort+incomeTax+
             pUnemp+agi_amt+numDepend+preTax+agi_bkt)
summary(model)

```
#### Linearity Assumption
```{r}
library(MASS)
resids = stdres(model)

par(mfrow=c(2,2))
plot(subData[,2],resids,xlab="credit_amt")
abline(0,0,col="red")

plot(subData[,3],resids,xlab="tax_income")
abline(0,0,col="red")

plot(subData[,4],resids,xlab="mortg_amt")
abline(0,0,col="red")

plot(subData[,5],resids,xlab="pMort")
abline(0,0,col="red")
```

```{r}
par(mfrow=c(2,2))
plot(subData[,6],resids,xlab="income_tax")
abline(0,0,col="red")

plot(subData[,7],resids,xlab="pUnemp")
abline(0,0,col="red")

plot(subData[,8],resids,xlab="agi_amt")
abline(0,0,col="red")

plot(subData[,9],resids,xlab="numDepend")
abline(0,0,col="red")
```
```{r}
par(mfrow=c(2,2))
plot(subData[,10],resids,xlab="preTax")
abline(0,0,col="red")

plot(subData[,11],resids,xlab="agi_bkt")
abline(0,0,col="red")
```

#### Residual Analysis: Other Assumptions
```{r}
library(car)
fits = model$fitted
cook = cooks.distance(model)
par(mfrow=c(2,2))
plot(fits,resids,xlab="Fitted Values",ylab="Residuals")
abline(0,0,col="red")
qqPlot(resids,ylab="Residuals",main="")
hist(resids,xlab="Residuals",main="",nclass=10,col="orange")
plot(cook,type="h",lwd=3,col="red",ylab="Cook's Distance")

```









